In [2155]:
# Import necessary packages
import pandas as pd
import numpy as np
import os,sys
import seaborn as sns


In [2156]:
# Check current working directory
os.getcwd()

'/Users/yeonjoo/Downloads/Unilateral_foot'

In [2157]:
# Change directory if necessary
#newdirectory = input("Path: ")
#os.chdir(newdirectory)
#os.getcwd()

In [2158]:
# File import by filename
Subject = input("Subject: ")
Trial = input("Trial: ")
filename = Subject + "Trial"+ Trial

df = pd.read_csv(filename +'.csv')
df.head()

Subject: G06
Trial: 07B


LHEEX        LHEEY       LHEEZ       LTOEX        LTOEY       LTOEZ  \
0    0.000000     0.000000    0.000000  319.084412 -1282.226440  227.481888   
1  302.348114 -1111.143677  244.230469  319.116913 -1280.674072  227.474960   
2  302.353668 -1109.587402  244.245346  319.164398 -1278.496948  227.468933   
3  302.363586 -1107.405029  244.266617  319.228302 -1275.678345  227.465042   
4  302.378967 -1104.579834  244.294586  319.309387 -1272.245605  227.463760   

        RHEEX       RHEEY       RHEEZ       RTOEX        RTOEY       RTOEZ  
0  253.936386 -917.947021  390.717865  216.447357  -998.099304  245.512314  
1  253.882431 -920.817993  389.634766  215.917175 -1002.554871  245.559372  
2  253.791367 -924.930603  387.990295  215.189453 -1008.906982  245.579803  
3  253.654129 -930.368835  385.700378  214.269394 -1017.264587  245.548569  
4  253.463181 -937.142151  382.706604  213.180984 -1027.615356  245.438431

In [2159]:
df = pd.read_csv(filename +'.csv')
df.head()

LHEEX        LHEEY       LHEEZ       LTOEX        LTOEY       LTOEZ  \
0    0.000000     0.000000    0.000000  319.084412 -1282.226440  227.481888   
1  302.348114 -1111.143677  244.230469  319.116913 -1280.674072  227.474960   
2  302.353668 -1109.587402  244.245346  319.164398 -1278.496948  227.468933   
3  302.363586 -1107.405029  244.266617  319.228302 -1275.678345  227.465042   
4  302.378967 -1104.579834  244.294586  319.309387 -1272.245605  227.463760   

        RHEEX       RHEEY       RHEEZ       RTOEX        RTOEY       RTOEZ  
0  253.936386 -917.947021  390.717865  216.447357  -998.099304  245.512314  
1  253.882431 -920.817993  389.634766  215.917175 -1002.554871  245.559372  
2  253.791367 -924.930603  387.990295  215.189453 -1008.906982  245.579803  
3  253.654129 -930.368835  385.700378  214.269394 -1017.264587  245.548569  
4  253.463181 -937.142151  382.706604  213.180984 -1027.615356  245.438431

In [2160]:
if any(df.iloc[0] == 0):
    df.drop([0], inplace=True)

df = df.reset_index(drop=True)
df.head()

LHEEX        LHEEY       LHEEZ       LTOEX        LTOEY       LTOEZ  \
0  302.348114 -1111.143677  244.230469  319.116913 -1280.674072  227.474960   
1  302.353668 -1109.587402  244.245346  319.164398 -1278.496948  227.468933   
2  302.363586 -1107.405029  244.266617  319.228302 -1275.678345  227.465042   
3  302.378967 -1104.579834  244.294586  319.309387 -1272.245605  227.463760   
4  302.400574 -1101.139648  244.329300  319.407776 -1268.259277  227.465363   

        RHEEX       RHEEY       RHEEZ       RTOEX        RTOEY       RTOEZ  
0  253.882431 -920.817993  389.634766  215.917175 -1002.554871  245.559372  
1  253.791367 -924.930603  387.990295  215.189453 -1008.906982  245.579803  
2  253.654129 -930.368835  385.700378  214.269394 -1017.264587  245.548569  
3  253.463181 -937.142151  382.706604  213.180984 -1027.615356  245.438431  
4  253.213348 -945.203247  378.977509  211.963745 -1039.850342  245.224182

In [2161]:
# Use Only When first rows are "0" =====> Need to code "IF"

#df.drop([0,0], inplace=True)
#df = df.reset_index(drop=True)
#df.head()

In [2162]:
df.head()

LHEEX        LHEEY       LHEEZ       LTOEX        LTOEY       LTOEZ  \
0  302.348114 -1111.143677  244.230469  319.116913 -1280.674072  227.474960   
1  302.353668 -1109.587402  244.245346  319.164398 -1278.496948  227.468933   
2  302.363586 -1107.405029  244.266617  319.228302 -1275.678345  227.465042   
3  302.378967 -1104.579834  244.294586  319.309387 -1272.245605  227.463760   
4  302.400574 -1101.139648  244.329300  319.407776 -1268.259277  227.465363   

        RHEEX       RHEEY       RHEEZ       RTOEX        RTOEY       RTOEZ  
0  253.882431 -920.817993  389.634766  215.917175 -1002.554871  245.559372  
1  253.791367 -924.930603  387.990295  215.189453 -1008.906982  245.579803  
2  253.654129 -930.368835  385.700378  214.269394 -1017.264587  245.548569  
3  253.463181 -937.142151  382.706604  213.180984 -1027.615356  245.438431  
4  253.213348 -945.203247  378.977509  211.963745 -1039.850342  245.224182

In [2163]:
# Calculate Heel and Toe Marker Velocity
col_names = ['LHEEY','RHEEY', 'LTOEY', 'RTOEY']
name_rows_dict1 = {}

for col in col_names:
    vel_rows = []
    for idx, value in enumerate(df[col]):
        if idx == 0:
            vel_rows.append(0)
        else:
            vel_row = (df.loc[idx,col] - df.loc[idx-1,col])*100
            vel_rows.append(vel_row)
    name_rows_dict1[col] = vel_rows

vel_df = pd.DataFrame(name_rows_dict1)
vel_df = vel_df.drop(0)
vel_df = vel_df.reset_index(drop=True)
vel_df.head(10)

LHEEY      RHEEY     LTOEY      RTOEY
0  155.6275  -411.2610  217.7124  -635.2111
1  218.2373  -543.8232  281.8603  -835.7605
2  282.5195  -677.3316  343.2740 -1035.0769
3  344.0186  -806.1096  398.6328 -1223.4986
4  399.3408  -926.1047  445.7519 -1394.1406
5  446.2524 -1034.9427  483.5327 -1542.5781
6  483.6670 -1131.5490  511.8409 -1666.7725
7  511.3892 -1216.0767  531.2500 -1766.5649
8  529.9804 -1289.2822  542.9687 -1843.2862
9  540.6617 -1352.4292  548.3643 -1899.1577

In [2239]:
# Identify Left Heel Strike
# by Left Heel marker velocity changes its direction
name_rows_dict2 = {}

lstrike_rows = []
for idx, value in enumerate(vel_df['LHEEY']):
    if idx == 0:
        idx = idx + 1
    else:
        if vel_df.loc[idx, 'LHEEY'] < 0:
            idx = idx + 1 
        else:
            if vel_df.loc[idx - 1, 'LHEEY'] > 0:
                idx = idx + 1 
            else:
                lstrike_rows.append(idx - 1)
            
name_rows_dict2['LHSidx'] = lstrike_rows

lstrike_df = pd.DataFrame(name_rows_dict2)
lstrike_df.head(), len(lstrike_df)

(   LHSidx
 0     101
 1     241
 2     389
 3     535
 4     669,
 205)

In [2165]:
#idx = 0

#lstrike_df.loc[idx]== 0

In [2166]:
#for idx in lstrike_df.index:
#    if lstrike_df.loc[idx] == 0:
#        lstrike_df.drop([idx])
#    else:
#        idx = idx + 1

#lstrike_df = df.reset_index(drop=True)
#lstrike_df.head()

In [2240]:
# Identify Left Toe Off
# by Left Toe marker velocity changes its direction
name_rows_dict3 = {}

ltoff_rows = []
for idx, value in enumerate(vel_df['LTOEY']):
    if idx == 0:
        idx = idx + 1
    else:
        if vel_df.loc[idx, 'LTOEY'] > 0:
            idx = idx + 1 
        else:
            if vel_df.loc[idx - 1, 'LTOEY'] < 0:
                
                
                idx = idx + 1 
            else:
                ltoff_rows.append(idx - 1)
            
name_rows_dict3['LTOidx'] = ltoff_rows

ltoff_df = pd.DataFrame(name_rows_dict3)
ltoff_df.head(), len(ltoff_df)

(   LTOidx
 0      56
 1     197
 2     344
 3     494
 4     629,
 205)

In [2241]:
# Identify left side repeated Heel Strike by its interval (first interval default 55)

lefts = []
for idx in lstrike_df.index:
    if idx == 0:
        lefts.append(55)
    else:
        left = (lstrike_df.loc[idx, 'LHSidx']- lstrike_df.loc[idx - 1, 'LHSidx'])
        lefts.append(left)

lstrike_df['lHSinterval'] = lefts
lstrike_df.head(), lstrike_df['lHSinterval'].unique(), lstrike_df.count()

(   LHSidx  lHSinterval
 0     101           55
 1     241          140
 2     389          148
 3     535          146
 4     669          134,
 array([ 55, 140, 148, 146, 134, 131, 144, 147, 123, 138, 152, 162, 154,
        143, 145, 156, 153, 161, 150, 164, 155, 149, 158, 130, 151, 135,
        141, 124, 137, 165, 133, 139, 118, 114, 125, 189, 166, 170, 176,
        167, 174, 136, 157, 127, 132, 179, 180, 160, 117, 109,  91, 128,
        112, 116,  95,  81, 126, 184, 142, 129, 122, 119, 173, 168, 172,
        163]),
 LHSidx         205
 lHSinterval    205
 dtype: int64)

In [2242]:
# Identify left side repeated Toe Off by its interval (first interval default 55)

lefts = []
for idx in ltoff_df.index:
    if idx == 0:
        lefts.append(55)
    else:
        left = (ltoff_df.loc[idx, 'LTOidx']- ltoff_df.loc[idx - 1, 'LTOidx'])
        lefts.append(left)

ltoff_df['lTOinterval'] = lefts
ltoff_df.head(), ltoff_df['lTOinterval'].unique(), ltoff_df.count()

(   LTOidx  lTOinterval
 0      56           55
 1     197          141
 2     344          147
 3     494          150
 4     629          135,
 array([ 55, 141, 147, 150, 135, 130, 140, 128, 133, 144, 152, 161, 153,
        145, 138, 146, 158, 162, 154, 151, 163, 156, 149, 160, 132, 136,
        129, 131, 155, 137, 148, 143, 142, 127, 116, 139, 188, 166, 159,
        174, 169, 167, 175, 157, 126, 179, 173, 115, 120,  92, 125, 119,
        123, 108, 100,  73, 117, 180, 112, 185, 172, 171, 168, 181]),
 LTOidx         205
 lTOinterval    205
 dtype: int64)

In [2218]:
len(lstrike_df[lstrike_df['lHSinterval'] < 55])

0

In [2243]:
lstrike_df.values[lstrike_df['lHSinterval'] < 100]

array([[  101,    55],
       [20492,    91],
       [21504,    95],
       [21585,    81]])

In [2172]:
len(ltoff_df[ltoff_df['lTOinterval'] < 55])

0

In [2245]:
ltoff_df.values[ltoff_df['lTOinterval'] < 100]

array([[   56,    55],
       [20462,    92],
       [21547,    73]])

In [2174]:
#Drop left side repeated Heel Strike
for idx, row in lstrike_df.iterrows():
    if row['lHSinterval'] < 55:
        lstrike_df.drop(idx, inplace=True)


lstrike_df.head(), lstrike_df['lHSinterval'].unique(), lstrike_df.count()

(   LHSidx  lHSinterval
 0     101           55
 1     241          140
 2     389          148
 3     535          146
 4     669          134,
 array([ 55, 140, 148, 146, 134, 131, 144, 147, 123, 138, 152, 162, 154,
        143, 145, 156, 153, 161, 150, 164, 155, 149, 158, 130, 151, 135,
        141, 124, 137, 165, 133, 139, 118, 114, 125, 189, 166, 170, 176,
        167, 174, 136, 157, 127, 132, 179, 180, 160, 117, 109,  91, 128,
        112, 116,  95,  81, 126, 184, 142, 129, 122, 119, 173, 168, 172,
        163]),
 LHSidx         205
 lHSinterval    205
 dtype: int64)

In [2175]:
#Drop left side repeated Toe Off
for idx, row in ltoff_df.iterrows():
    if row['lTOinterval'] < 55:
        ltoff_df.drop(idx, inplace=True)


ltoff_df.head(), ltoff_df['lTOinterval'].unique(), ltoff_df.count()

(   LTOidx  lTOinterval
 0      56           55
 1     197          141
 2     344          147
 3     494          150
 4     629          135,
 array([ 55, 141, 147, 150, 135, 130, 140, 128, 133, 144, 152, 161, 153,
        145, 138, 146, 158, 162, 154, 151, 163, 156, 149, 160, 132, 136,
        129, 131, 155, 137, 148, 143, 142, 127, 116, 139, 188, 166, 159,
        174, 169, 167, 175, 157, 126, 179, 173, 115, 120,  92, 125, 119,
        123, 108, 100,  73, 117, 180, 112, 185, 172, 171, 168, 181]),
 LTOidx         205
 lTOinterval    205
 dtype: int64)

In [2176]:
#Concate HS and TO event time & make sure them to be int 64
lstrike_df = pd.concat([lstrike_df,ltoff_df], axis=1)
lstrike_df = lstrike_df.astype('Int64')
lstrike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval
0     101           55      56           55
1     241          140     197          141
2     389          148     344          147
3     535          146     494          150
4     669          134     629          135

In [2177]:
# Reset the index for left foot
lstrike_df = lstrike_df.reset_index(drop=True)
lstrike_df = lstrike_df.dropna()
lstrike_df.head(), len(lstrike_df)

(   LHSidx  lHSinterval  LTOidx  lTOinterval
 0     101           55      56           55
 1     241          140     197          141
 2     389          148     344          147
 3     535          146     494          150
 4     669          134     629          135,
 205)

In [2178]:
# Get trajectory for left heelstrike and left toeoff
LHSval = pd.DataFrame(df.loc[lstrike_df['LHSidx'], ['LHEEX','LHEEY']])
LHSval_reidx = LHSval.reset_index().drop(columns=['index'])

LTOval = pd.DataFrame(df.loc[lstrike_df['LTOidx'], ['LTOEY','LTOEZ']])
LTOval_reidx = LTOval.reset_index().drop(columns=['index'])


In [2179]:
# Concate the left HS and TO
LHS_df = pd.concat([lstrike_df, LHSval_reidx, LTOval_reidx], axis=1)
LHS_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  
0 -1010.393738  227.602692  
1 -1018.445496  226.731796  
2 -1013.258362  226.802200  
3 -1027.757568  225.482666  
4 -1043.392700  227.512695

In [2180]:
#NEW!!!! #Identify right heel strike
name_rows_dict4 = {}

rstrike_rows = []
for idx, value in enumerate(vel_df['RHEEY']):
    if idx == 0:
        idx = idx + 1
    else:
        if vel_df.loc[idx, 'RHEEY'] < 0:
            idx = idx + 1 
        else:
            if vel_df.loc[idx - 1, 'RHEEY'] > 0:
                idx = idx + 1 
            else:
                rstrike_rows.append(idx - 1)
            
name_rows_dict4['RHSidx'] = rstrike_rows

rstrike_df = pd.DataFrame(name_rows_dict4)
rstrike_df.head(), len(rstrike_df)

(   RHSidx
 0      33
 1     172
 2     311
 3     461
 4     599,
 206)

In [2181]:
# Identify Right Toe Off
# by Right Toe marker velocity changes its direction from positive to negative
name_rows_dict5 = {}

rtoff_rows = []
for idx, value in enumerate(vel_df['RTOEY']):
    if idx == 0:
        idx = idx + 1
    else:
        if vel_df.loc[idx, 'RTOEY'] > 0:
            idx = idx + 1 
        else:
            if vel_df.loc[idx - 1, 'RTOEY'] < 0:
                idx = idx + 1 
            else:
                rtoff_rows.append(idx - 1)
            
name_rows_dict5['RTOidx'] = rtoff_rows

rtoff_df = pd.DataFrame(name_rows_dict5)
rtoff_df.head(), len(rtoff_df)

(   RTOidx
 0     129
 1     270
 2     418
 3     562
 4     697,
 207)

In [2182]:
# Identify right side repeated Heel Strike (first interval default 55)

rights = []
for idx in rstrike_df.index:
    if idx == 0:
        rights.append(55)
    else:
        right = (rstrike_df.loc[idx, 'RHSidx']- rstrike_df.loc[idx - 1, 'RHSidx'])
        rights.append(right)

rstrike_df['rHSinterval'] = rights
rstrike_df.head(), rstrike_df['rHSinterval'].unique(),  rstrike_df.count()

(   RHSidx  rHSinterval
 0      33           55
 1     172          139
 2     311          139
 3     461          150
 4     599          138,
 array([ 55, 139, 150, 138, 133, 141, 145, 132, 127, 144, 152, 156, 157,
        148, 136, 137, 161, 147, 155, 158, 160, 154, 151, 159, 149, 153,
        165, 134, 140, 124, 128, 142, 143, 105, 146, 194, 169,  40, 176,
        168, 131, 135, 123, 162, 187, 115, 121,  96,  90, 112, 101,  81,
        107, 122, 186, 183, 119, 163, 117, 111, 130, 177, 170, 180]),
 RHSidx         206
 rHSinterval    206
 dtype: int64)

In [2183]:
# Identify right side repeated Toe Off (first interval default 55)

rights = []
for idx in rtoff_df.index:
    if idx == 0:
        rights.append(55)
    else:
        right = (rtoff_df.loc[idx, 'RTOidx']- rtoff_df.loc[idx - 1, 'RTOidx'])
        rights.append(right)

rtoff_df['rTOinterval'] = rights
rtoff_df.head(), rtoff_df['rTOinterval'].unique(),  rtoff_df.count()

(   RTOidx  rTOinterval
 0     129           55
 1     270          141
 2     418          148
 3     562          144
 4     697          135,
 array([ 55, 141, 148, 144, 135, 134, 147, 124, 158, 157, 136, 142, 153,
        154, 156, 161, 155, 159, 151, 162, 137, 149, 139, 114, 160, 145,
        130, 146, 138, 127, 126, 193, 167, 143,  65, 117,  27, 172, 140,
        122, 150, 133, 132, 129, 152, 121, 166, 184, 164, 105, 125,  95,
        100,  81,  98, 119, 131, 116, 187, 123, 118, 115, 170, 185, 163,
        173, 169, 186]),
 RTOidx         207
 rTOinterval    207
 dtype: int64)

In [2184]:
len(rstrike_df[rstrike_df['rHSinterval'] < 55]) 

1

In [2185]:
#rstrike_df.values[rstrike_df['rHSinterval'] < 55]

In [2186]:
len(rtoff_df[rtoff_df['rTOinterval'] < 55])

1

In [2187]:
#rtoff_df.values[rtoff_df['rTOinterval'] < 55]

In [2188]:
#Drop right side repeated Heel Strike
for idx, row in rstrike_df.iterrows():
    if row['rHSinterval'] < 55:
        rstrike_df.drop(idx, inplace=True)

rstrike_df.head(), rstrike_df['rHSinterval'].unique(), rstrike_df.count()

(   RHSidx  rHSinterval
 0      33           55
 1     172          139
 2     311          139
 3     461          150
 4     599          138,
 array([ 55, 139, 150, 138, 133, 141, 145, 132, 127, 144, 152, 156, 157,
        148, 136, 137, 161, 147, 155, 158, 160, 154, 151, 159, 149, 153,
        165, 134, 140, 124, 128, 142, 143, 105, 146, 194, 169, 176, 168,
        131, 135, 123, 162, 187, 115, 121,  96,  90, 112, 101,  81, 107,
        122, 186, 183, 119, 163, 117, 111, 130, 177, 170, 180]),
 RHSidx         205
 rHSinterval    205
 dtype: int64)

In [2189]:
#Drop right side repeated Toe Off
for idx, row in rtoff_df.iterrows():
    if row['rTOinterval'] < 55:
        rtoff_df.drop(idx, inplace=True)

rtoff_df.head(), rtoff_df['rTOinterval'].unique(), rtoff_df.count()

(   RTOidx  rTOinterval
 0     129           55
 1     270          141
 2     418          148
 3     562          144
 4     697          135,
 array([ 55, 141, 148, 144, 135, 134, 147, 124, 158, 157, 136, 142, 153,
        154, 156, 161, 155, 159, 151, 162, 137, 149, 139, 114, 160, 145,
        130, 146, 138, 127, 126, 193, 167, 143,  65, 117, 172, 140, 122,
        150, 133, 132, 129, 152, 121, 166, 184, 164, 105, 125,  95, 100,
         81,  98, 119, 131, 116, 187, 123, 118, 115, 170, 185, 163, 173,
        169, 186]),
 RTOidx         206
 rTOinterval    206
 dtype: int64)

In [2190]:
#Concate HS and TO event time & make sure them to be int 64
rstrike_df = pd.concat([rstrike_df,rtoff_df], axis=1)
rstrike_df = rstrike_df.astype('Int64')
rstrike_df.head()

RHSidx  rHSinterval  RTOidx  rTOinterval
0      33           55     129           55
1     172          139     270          141
2     311          139     418          148
3     461          150     562          144
4     599          138     697          135

In [2191]:
# Reset the index for right foot
rstrike_df = rstrike_df.reset_index(drop=True)
rstrike_df = rstrike_df.dropna()
rstrike_df.head(), len(rstrike_df)

(   RHSidx  rHSinterval  RTOidx  rTOinterval
 0      33           55     129           55
 1     172          139     270          141
 2     311          139     418          148
 3     461          150     562          144
 4     599          138     697          135,
 204)

In [2192]:
# Get trajectory for left heelstrike and left toeoff
RHSval = pd.DataFrame(df.loc[rstrike_df['RHSidx'], ['RHEEX','RHEEY']])
RHSval_reidx = RHSval.reset_index().drop(columns=['index'])

RTOval = pd.DataFrame(df.loc[rstrike_df['RTOidx'], ['RTOEY','RTOEZ']])
RTOval_reidx = RTOval.reset_index().drop(columns=['index'])


In [2193]:
# Concate the right HS and TO
RHS_df = pd.concat([rstrike_df, RHSval_reidx, RTOval_reidx], axis=1)
RHS_df.head()

RHSidx  rHSinterval  RTOidx  rTOinterval       RHEEX        RHEEY  \
0      33           55     129           55  233.540054 -1286.068481   
1     172          139     270          141  252.852020 -1336.528320   
2     311          139     418          148  234.913055 -1371.892578   
3     461          150     562          144  222.596786 -1316.693848   
4     599          138     697          135  257.942108 -1279.066040   

         RTOEY       RTOEZ  
0 -1011.603333  228.053497  
1 -1050.903198  224.890610  
2 -1040.803101  228.082809  
3 -1009.212158  228.511887  
4  -978.586609  227.261932

In [2194]:
# Merge left and right side HS and TO 
strike_df = pd.merge(LHS_df, RHS_df, left_index = True, right_index = True)
strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  RTOidx  rTOinterval  \
0 -1010.393738  227.602692      33           55     129           55   
1 -1018.445496  226.731796     172          139     270          141   
2 -1013.258362  226.802200     311          139     418          148   
3 -1027.757568  225.482666     461          150     562          144   
4 -1043.392700  227.512695     599          138     697          135   

        RHEEX        RHEEY        RTOEY       RTOEZ  
0  233.540054 -1286.068481 -1011.603333  228.053497  
1  252.852020 -1336.528320 -1050.903198  224.890610  
2  234.913055 -1371.892578 -1040.803101  228.082809  
3  222.596786 -1316.693848 -1009.212158  228.511887  
4  257.942108 -1279.066040  -978.586609  227.261932

In [2195]:
# Calculate step time


Rsteptime = []
Lsteptime = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'RHSidx']:
        if idx == 0:
            Rstep_time = strike_df.loc[idx, 'RHSidx'] - strike_df.loc[idx, 'LHSidx']
            Rsteptime.append(Rstep_time)
            Lsteptime.append(0)
        else:
            Rstep_time = strike_df.loc[idx, 'RHSidx'] - strike_df.loc[idx, 'LHSidx']
            Rsteptime.append(Rstep_time)
            Lstep_time = strike_df.loc[idx, 'LHSidx'] - strike_df.loc[idx - 1,'RHSidx']
            Lsteptime.append(Lstep_time)
    else:
        if idx ==0:
            Rsteptime.append(0)
            Lstep_time = strike_df.loc[idx, 'LHSidx'] - strike_df.loc[idx,'RHSidx']
            Lsteptime.append(Lstep_time)
        else:
            Rstep_time = strike_df.loc[idx, 'RHSidx'] - strike_df.loc[idx - 1, 'LHSidx']
            Rsteptime.append(Rstep_time)
            Lstep_time = strike_df.loc[idx, 'LHSidx'] - strike_df.loc[idx,'RHSidx']
            Lsteptime.append(Lstep_time)
        

strike_df['Rstep_time'] = Rsteptime
strike_df['Lstep_time'] = Lsteptime

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  RTOidx  rTOinterval  \
0 -1010.393738  227.602692      33           55     129           55   
1 -1018.445496  226.731796     172          139     270          141   
2 -1013.258362  226.802200     311          139     418          148   
3 -1027.757568  225.482666     461          150     562          144   
4 -1043.392700  227.512695     599          138     697          135   

        RHEEX        RHEEY        RTOEY       RTOEZ Rstep_time Lstep_time  
0  233.540054 -1286.068481 -1011.603333  228.053497          0         68  
1  252.852020 -1336.528320 -1050.903198  224.890610         71         69  
2  234.913055 -1371.892578 -1040.803101  228.082809         70         78  
3  222.596786 -1316.693848 -1009.212158  228.511887         72         74  
4  257.942108 -1279.066040  -978.586609  227.261932         64         70

In [2196]:
strike_df.tail()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
200   29251          170   29201          166  303.076904 -1227.972290   
201   29416          165   29369          168  308.208038 -1242.303711   
202   29579          163   29532          163  311.286743 -1268.972534   
203   29759          180   29713          181  318.802216 -1169.336304   
204   29926          167   29875          162  318.103729 -1188.662842   

          LTOEY       LTOEZ  RHSidx  rHSinterval  RTOidx  rTOinterval  \
200 -805.587708  225.680328   29173          169   29122          169   
201 -801.716431  226.477280   29329          156   29284          162   
202 -825.054321  229.674850   29497          168   29444          160   
203 -750.709351  228.422745   29677          180   29630          186   
204 -758.283447  227.652954   29842          165   29794          164   

          RHEEX        RHEEY       RTOEY       RTOEZ Rstep_time Lstep_time  
200  272.868927 -1227.922729 -843.241821  228.485641         92         78  
201  282.418823 -1314.848999 -780.487915  230.280991         78         87  
202  266.633575 -1204.441528 -794.795105  227.356873         81         82  
203  311.332397 -1172.561768 -768.436646  226.734772         98         82  
204         NaN          NaN         NaN         NaN         83         84

In [2197]:
strike_df['Rstep_time'].unique()

array([0, 71, 70, 72, 64, 63, 73, 74, 59, 69, 77, 81, 76, 66, 82, 80, 88,
       78, 75, 68, 79, 83, 67, 65, 61, 86, 89, 62, 49, 120, 84, <NA>, 100,
       58, 57, 55, 46, 45, 60, 85, 52, 38, 99, 87, 56, 51, 109, 95, 94,
       91, 92, 98], dtype=object)

In [2198]:
strike_df['Lstep_time'].unique()

array([68, 69, 78, 74, 70, 71, 73, 64, 75, 81, 79, 76, 77, 80, 72, 84, 82,
       63, 57, 86, 65, 61, 83, 56, 59, 87, 88, 108, <NA>, 92, 66, 67, 91,
       107, 60, 62, 50, 45, 52, 49, 43, 55, 105, 93, 102, 89, 90],
      dtype=object)

In [2199]:
# Get Treadmil Belt Speed
input_val = pd.read_csv('input_val.csv')
input_val = input_val.set_index('Unnamed: 0')
beltspeed = input_val.loc[Subject, 'belt_speed']
beltspeed, type(beltspeed)

(0.49, numpy.float64)

In [2200]:
#Calculate Step Length

Rsteplength = []
Lsteplength = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'RHSidx']:
        if idx == 0:
            Rstep_length = strike_df.loc[idx, 'RHEEY'] - (strike_df.loc[idx, 'LHEEY'] - (beltspeed*strike_df.loc[idx, 'Rstep_time']*10))
            Rsteplength.append(Rstep_length)
            Lsteplength.append(0)
        else:
            Rstep_length = strike_df.loc[idx, 'RHEEY'] - (strike_df.loc[idx, 'LHEEY'] - (beltspeed*strike_df.loc[idx, 'Rstep_time']*10))
            Rsteplength.append(Rstep_length)
            Lstep_length = strike_df.loc[idx, 'LHEEY'] - (strike_df.loc[idx - 1,'RHEEY']-(beltspeed*strike_df.loc[idx, 'Lstep_time']*10))
            Lsteplength.append(Lstep_length)
    else:
        if idx ==0:
            Rsteplength.append(0)
            Lstep_length = strike_df.loc[idx, 'LHEEY'] - (strike_df.loc[idx,'RHEEY']-(beltspeed*strike_df.loc[idx, 'Lstep_time']*10))
            Lsteplength.append(Lstep_length)
        else:
            Rstep_length = strike_df.loc[idx, 'RHEEY'] - (strike_df.loc[idx - 1, 'LHEEY'] - (beltspeed*strike_df.loc[idx, 'Rstep_time']*10))
            Rsteplength.append(Rstep_length)
            Lstep_length = strike_df.loc[idx, 'LHEEY'] - (strike_df.loc[idx,'RHEEY']-(beltspeed*strike_df.loc[idx, 'Lstep_time']*10))
            Lsteplength.append(Lstep_length)
        

strike_df['Rstep_length'] = Rsteplength
strike_df['Lstep_length'] = Lsteplength

strike_df.tail()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
200   29251          170   29201          166  303.076904 -1227.972290   
201   29416          165   29369          168  308.208038 -1242.303711   
202   29579          163   29532          163  311.286743 -1268.972534   
203   29759          180   29713          181  318.802216 -1169.336304   
204   29926          167   29875          162  318.103729 -1188.662842   

          LTOEY       LTOEZ  RHSidx  rHSinterval  RTOidx  rTOinterval  \
200 -805.587708  225.680328   29173          169   29122          169   
201 -801.716431  226.477280   29329          156   29284          162   
202 -825.054321  229.674850   29497          168   29444          160   
203 -750.709351  228.422745   29677          180   29630          186   
204 -758.283447  227.652954   29842          165   29794          164   

          RHEEX        RHEEY       RTOEY       RTOEZ Rstep_time Lstep_time  \
200  272.868927 -1227.922729 -843.241821  228.485641         92         78   
201  282.418823 -1314.848999 -780.487915  230.280991         78         87   
202  266.633575 -1204.441528 -794.795105  227.356873         81         82   
203  311.332397 -1172.561768 -768.436646  226.734772         98         82   
204         NaN          NaN         NaN         NaN         83         84   

    Rstep_length Lstep_length  
200   466.177686   382.150439  
201   295.323291   498.845288  
202   434.762183   337.268994  
203   576.610766   405.025464  
204          NaN          NaN

In [2201]:
#Calculate Step Width

Rstepwidth = []
Lstepwidth = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'RHSidx']:
        if idx == 0:
            Rstep_width = abs(strike_df.loc[idx, 'RHEEX'] - (strike_df.loc[idx, 'LHEEX']))
            Rstepwidth.append(Rstep_width)
            Lstepwidth.append(0)
        else:
            Rstep_width = abs(strike_df.loc[idx, 'RHEEX'] - (strike_df.loc[idx, 'LHEEX']))
            Rstepwidth.append(Rstep_width)
            Lstep_width = abs(strike_df.loc[idx, 'LHEEX'] - (strike_df.loc[idx - 1,'RHEEX']))
            Lstepwidth.append(Lstep_width)
    else:
        if idx ==0:
            Rstepwidth.append(0)
            Lstep_width = abs(strike_df.loc[idx, 'LHEEX'] - (strike_df.loc[idx,'RHEEX']))
            Lstepwidth.append(Lstep_width)
        else:
            Rstep_width = abs(strike_df.loc[idx, 'RHEEX'] - (strike_df.loc[idx - 1, 'LHEEX']))
            Rstepwidth.append(Rstep_width)
            Lstep_width = abs(strike_df.loc[idx, 'LHEEX'] - (strike_df.loc[idx,'RHEEX']))
            Lstepwidth.append(Lstep_width)
        

strike_df['Rstep_width'] = Rstepwidth
strike_df['Lstep_width'] = Lstepwidth

strike_df.tail()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
200   29251          170   29201          166  303.076904 -1227.972290   
201   29416          165   29369          168  308.208038 -1242.303711   
202   29579          163   29532          163  311.286743 -1268.972534   
203   29759          180   29713          181  318.802216 -1169.336304   
204   29926          167   29875          162  318.103729 -1188.662842   

          LTOEY       LTOEZ  RHSidx  rHSinterval  ...       RHEEX  \
200 -805.587708  225.680328   29173          169  ...  272.868927   
201 -801.716431  226.477280   29329          156  ...  282.418823   
202 -825.054321  229.674850   29497          168  ...  266.633575   
203 -750.709351  228.422745   29677          180  ...  311.332397   
204 -758.283447  227.652954   29842          165  ...         NaN   

           RHEEY       RTOEY       RTOEZ  Rstep_time  Lstep_time Rstep_length  \
200 -1227.922729 -843.241821  228.485641          92          78   466.177686   
201 -1314.848999 -780.487915  230.280991          78          87   295.323291   
202 -1204.441528 -794.795105  227.356873          81          82   434.762183   
203 -1172.561768 -768.436646  226.734772          98          82   576.610766   
204          NaN         NaN         NaN          83          84          NaN   

    Lstep_length Rstep_width Lstep_width  
200   382.150439   89.133179   30.207977  
201   498.845288   20.658081   25.789215  
202   337.268994   41.574463   44.653168  
203   405.025464    0.045654    7.469819  
204          NaN         NaN         NaN  

[5 rows x 22 columns]

In [2202]:
# Calculate Stance time


Rstancetime = []
Lstancetime = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'LTOidx']:
        Lstance_time = strike_df.loc[idx, 'LTOidx'] - strike_df.loc[idx, 'LHSidx']
        Lstancetime.append(Lstance_time)
        
    else:
        if idx == 0:
            Lstancetime.append(0)
        else:
            Lstance_time = strike_df.loc[idx, 'LTOidx'] - strike_df.loc[idx - 1, 'LHSidx']
            Lstancetime.append(Lstance_time)

for idx in strike_df.index:
    if strike_df.loc[0, 'RHSidx'] < strike_df.loc[0, 'RTOidx']:
        Rstance_time = strike_df.loc[idx, 'RTOidx'] - strike_df.loc[idx, 'RHSidx']
        Rstancetime.append(Rstance_time)
        
    else:
        if idx == 0:
            Rstancetime.append(0)
        else:
            Rstance_time = strike_df.loc[idx, 'RTOidx'] - strike_df.loc[idx - 1, 'RHSidx']
            Rstancetime.append(Rstance_time)
            

strike_df['Rstance_time'] = Rstancetime
strike_df['Lstance_time'] = Lstancetime

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...        RTOEY       RTOEZ  \
0 -1010.393738  227.602692      33           55  ... -1011.603333  228.053497   
1 -1018.445496  226.731796     172          139  ... -1050.903198  224.890610   
2 -1013.258362  226.802200     311          139  ... -1040.803101  228.082809   
3 -1027.757568  225.482666     461          150  ... -1009.212158  228.511887   
4 -1043.392700  227.512695     599          138  ...  -978.586609  227.261932   

   Rstep_time  Lstep_time  Rstep_length  Lstep_length Rstep_width Lstep_width  \
0           0          68             0    313.248095    0.000000   86.126053   
1          71          69    317.392066    348.240381   66.814087   57.980866   
2          70          78    297.495361    394.733691   75.919831   78.076081   
3          72          74    395.465039    355.647852   90.392350  115.510514   
4          64          70    358.179956    320.070557   80.165192   75.547638   

  Rstance_time Lstance_time  
0           96            0  
1           98           96  
2          107          103  
3          101          105  
4           98           94  

[5 rows x 24 columns]

In [2203]:
# Calculate Swing time


Rswingtime = []
Lswingtime = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'LTOidx']:
        if idx == 0:
            Lswingtime.append(0)
        else:
            Lswing_time = strike_df.loc[idx, 'LHSidx'] - strike_df.loc[idx - 1,'LTOidx']
            Lswingtime.append(Lswing_time)
    else:
        Lswing_time = strike_df.loc[idx, 'LHSidx'] - strike_df.loc[idx,'LTOidx']
        Lswingtime.append(Lswing_time)

for idx in strike_df.index:
    if strike_df.loc[0, 'RHSidx'] < strike_df.loc[0, 'RTOidx']:
        if idx == 0:
            Rswingtime.append(0)
        else:
            Rswing_time = strike_df.loc[idx, 'RHSidx'] - strike_df.loc[idx - 1,'RTOidx']
            Rswingtime.append(Rswing_time)
    else:
        Rswing_time = strike_df.loc[idx, 'RHSidx'] - strike_df.loc[idx,'RTOidx']
        Rswingtime.append(Rswing_time)
        
        

strike_df['Rswing_time'] = Rswingtime
strike_df['Lswing_time'] = Lswingtime

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...  Rstep_time  Lstep_time  \
0 -1010.393738  227.602692      33           55  ...           0          68   
1 -1018.445496  226.731796     172          139  ...          71          69   
2 -1013.258362  226.802200     311          139  ...          70          78   
3 -1027.757568  225.482666     461          150  ...          72          74   
4 -1043.392700  227.512695     599          138  ...          64          70   

   Rstep_length  Lstep_length  Rstep_width  Lstep_width Rstance_time  \
0             0    313.248095     0.000000    86.126053           96   
1    317.392066    348.240381    66.814087    57.980866           98   
2    297.495361    394.733691    75.919831    78.076081          107   
3    395.465039    355.647852    90.392350   115.510514          101   
4    358.179956    320.070557    80.165192    75.547638           98   

  Lstance_time Rswing_time Lswing_time  
0            0           0          45  
1           96          43          44  
2          103          41          45  
3          105          43          41  
4           94          37          40  

[5 rows x 26 columns]

In [2204]:
# Caculate stance and swing in %

Rstance = []
Lstance = []
Rswing = []
Lswing = []


for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'LTOidx']:
        if idx == 0:
            Lstance.append(0)
            Lswing.append(0) 
        else:
            Lstance_per = (strike_df.loc[idx - 1, 'Lstance_time']/(strike_df.loc[idx, 'Lswing_time'] + strike_df.loc[idx - 1,'Lstance_time']))*100
            Lstance.append(Lstance_per)
            Lswing_per = (strike_df.loc[idx, 'Lswing_time']/(strike_df.loc[idx, 'Lswing_time'] + strike_df.loc[idx - 1,'Lstance_time']))*100
            Lswing.append(Lswing_per)
    else:
        if idx == 0:
            Lstance.append(0)
            Lswing.append(0) 
        else:
            Lstance_per = (strike_df.loc[idx, 'Lstance_time']/(strike_df.loc[idx - 1, 'Lswing_time'] + strike_df.loc[idx,'Lstance_time']))*100
            Lstance.append(Lstance_per)
            Lswing_per = (strike_df.loc[idx - 1, 'Lswing_time']/(strike_df.loc[idx - 1, 'Lswing_time'] + strike_df.loc[idx,'Lstance_time']))*100
            Lswing.append(Lswing_per)

for idx in strike_df.index:
    if strike_df.loc[0, 'RHSidx'] < strike_df.loc[0, 'RTOidx']:
        if idx == 0:
            Rstance.append(0)
            Rswing.append(0) 
        else:
            Rstance_per = (strike_df.loc[idx - 1, 'Rstance_time']/(strike_df.loc[idx, 'Rswing_time'] + strike_df.loc[idx - 1,'Rstance_time']))*100
            Rstance.append(Rstance_per)
            Rswing_per = (strike_df.loc[idx, 'Rswing_time']/(strike_df.loc[idx, 'Rswing_time'] + strike_df.loc[idx - 1,'Rstance_time']))*100
            Rswing.append(Rswing_per)
    else:
        if idx == 0:
            Rstance.append(0)
            Rswing.append(0) 
        else:
            Rstance_per = (strike_df.loc[idx, 'Rstance_time']/(strike_df.loc[idx - 1, 'Rswing_time'] + strike_df.loc[idx,'Rstance_time']))*100
            Rstance.append(Rstance_per)
            Rswing_per = (strike_df.loc[idx - 1, 'Rswing_time']/(strike_df.loc[idx - 1, 'Rswing_time'] + strike_df.loc[idx,'Rstance_time']))*100
            Rswing.append(Rswing_per)
        

strike_df['Rstance%'] = Rstance
strike_df['Lstance%'] = Lstance
strike_df['Rswing%'] = Rswing
strike_df['Lswing%'] = Lswing

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...  Rstep_width  \
0 -1010.393738  227.602692      33           55  ...     0.000000   
1 -1018.445496  226.731796     172          139  ...    66.814087   
2 -1013.258362  226.802200     311          139  ...    75.919831   
3 -1027.757568  225.482666     461          150  ...    90.392350   
4 -1043.392700  227.512695     599          138  ...    80.165192   

   Lstep_width  Rstance_time  Lstance_time  Rswing_time  Lswing_time  \
0    86.126053            96             0            0           45   
1    57.980866            98            96           43           44   
2    78.076081           107           103           41           45   
3   115.510514           101           105           43           41   
4    75.547638            98            94           37           40   

    Rstance%   Lstance%    Rswing%    Lswing%  
0          0   0.000000          0   0.000000  
1  69.064748  68.085106  30.935252  31.914894  
2  70.503597  70.068027  29.496403  29.931973  
3  71.333333  70.000000  28.666667  30.000000  
4  73.188406  69.629630  26.811594  30.370370  

[5 rows x 30 columns]

In [2205]:
# Calculate stride time

Rstridetime = []
Lstridetime = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'RHSidx']:
        if idx == 0:
            Rstridetime.append(0)
            Lstridetime.append(0)
        else:
            Rstride_time = strike_df.loc[idx, 'Lstep_time'] + strike_df.loc[idx, 'Rstep_time']
            Rstridetime.append(Rstride_time)
            Lstride_time = strike_df.loc[idx - 1, 'Rstep_time'] + strike_df.loc[idx, 'Lstep_time']
            Lstridetime.append(Lstride_time)
    else:
        if idx ==0:
            Rstridetime.append(0)
            Lstridetime.append(0)
        else:
            Rstride_time = strike_df.loc[idx - 1, 'Lstep_time'] + strike_df.loc[idx, 'Rstep_time']
            Rstridetime.append(Rstride_time)
            Lstride_time = strike_df.loc[idx, 'Rstep_time'] + strike_df.loc[idx, 'Lstep_time']
            Lstridetime.append(Lstride_time)
        

strike_df['Rstride_time'] = Rstridetime
strike_df['Lstride_time'] = Lstridetime

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...  Rstance_time  \
0 -1010.393738  227.602692      33           55  ...            96   
1 -1018.445496  226.731796     172          139  ...            98   
2 -1013.258362  226.802200     311          139  ...           107   
3 -1027.757568  225.482666     461          150  ...           101   
4 -1043.392700  227.512695     599          138  ...            98   

   Lstance_time  Rswing_time  Lswing_time   Rstance%   Lstance%    Rswing%  \
0             0            0           45          0   0.000000          0   
1            96           43           44  69.064748  68.085106  30.935252   
2           103           41           45  70.503597  70.068027  29.496403   
3           105           43           41  71.333333  70.000000  28.666667   
4            94           37           40  73.188406  69.629630  26.811594   

     Lswing% Rstride_time Lstride_time  
0   0.000000            0            0  
1  31.914894          139          140  
2  29.931973          139          148  
3  30.000000          150          146  
4  30.370370          138          134  

[5 rows x 32 columns]

In [2206]:
# Calculate stride length

Rstridelength = []
Lstridelength = []

for idx in strike_df.index:
    if strike_df.loc[0, 'LHSidx'] < strike_df.loc[0, 'RHSidx']:
        if idx == 0:
            Rstridelength.append(0)
            Lstridelength.append(0)
        else:
            Rstride_length = strike_df.loc[idx, 'Lstep_length'] + strike_df.loc[idx, 'Rstep_length']
            Rstridelength.append(Rstride_length)
            Lstride_length = strike_df.loc[idx - 1, 'Rstep_length'] + strike_df.loc[idx, 'Lstep_length']
            Lstridelength.append(Lstride_length)
    else:
        if idx ==0:
            Rstridelength.append(0)
            Lstridelength.append(0)
        else:
            Rstride_length = strike_df.loc[idx - 1, 'Lstep_length'] + strike_df.loc[idx, 'Rstep_length']
            Rstridelength.append(Rstride_length)
            Lstride_length = strike_df.loc[idx, 'Rstep_length'] + strike_df.loc[idx, 'Lstep_length']
            Lstridelength.append(Lstride_length)
        

strike_df['Rstride_length'] = Rstridelength
strike_df['Lstride_length'] = Lstridelength

strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     101           55      56           55  319.666107 -1306.020386   
1     241          140     197          141  310.832886 -1326.387939   
2     389          148     344          147  312.989136 -1359.358887   
3     535          146     494          150  338.107300 -1323.645996   
4     669          134     629          135  333.489746 -1301.995483   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...  Rswing_time  \
0 -1010.393738  227.602692      33           55  ...            0   
1 -1018.445496  226.731796     172          139  ...           43   
2 -1013.258362  226.802200     311          139  ...           41   
3 -1027.757568  225.482666     461          150  ...           43   
4 -1043.392700  227.512695     599          138  ...           37   

   Lswing_time   Rstance%   Lstance%    Rswing%    Lswing% Rstride_time  \
0           45          0   0.000000          0   0.000000            0   
1           44  69.064748  68.085106  30.935252  31.914894          139   
2           45  70.503597  70.068027  29.496403  29.931973          139   
3           41  71.333333  70.000000  28.666667  30.000000          150   
4           40  73.188406  69.629630  26.811594  30.370370          138   

  Lstride_time Rstride_length Lstride_length  
0            0              0              0  
1          140     630.640161     665.632447  
2          148     645.735742     692.229052  
3          146      790.19873     751.112891  
4          134     713.827808     678.250513  

[5 rows x 34 columns]

In [2207]:
# Save spatiotemporal data in csv 

strike_df.to_csv(filename + '_data.csv',  index=False)

In [2208]:
#Drop first row if it contains 0

if any(strike_df.iloc[0] == 0):
    strike_df.drop([0], inplace=True)

strike_df = strike_df.reset_index(drop=True)
strike_df.head()

LHSidx  lHSinterval  LTOidx  lTOinterval       LHEEX        LHEEY  \
0     241          140     197          141  310.832886 -1326.387939   
1     389          148     344          147  312.989136 -1359.358887   
2     535          146     494          150  338.107300 -1323.645996   
3     669          134     629          135  333.489746 -1301.995483   
4     800          131     759          130  365.726807 -1267.215454   

         LTOEY       LTOEZ  RHSidx  rHSinterval  ...  Rswing_time  \
0 -1018.445496  226.731796     172          139  ...           43   
1 -1013.258362  226.802200     311          139  ...           41   
2 -1027.757568  225.482666     461          150  ...           43   
3 -1043.392700  227.512695     599          138  ...           37   
4 -1047.931519  237.565323     732          133  ...           35   

   Lswing_time   Rstance%   Lstance%    Rswing%    Lswing% Rstride_time  \
0           44  69.064748  68.085106  30.935252  31.914894          139   
1           45  70.503597  70.068027  29.496403  29.931973          139   
2           41  71.333333  70.000000  28.666667  30.000000          150   
3           40  73.188406  69.629630  26.811594  30.370370          138   
4           41  73.684211  69.230769  26.315789  30.769231          133   

  Lstride_time Rstride_length Lstride_length  
0          140     630.640161     665.632447  
1          148     645.735742     692.229052  
2          146      790.19873     751.112891  
3          134     713.827808     678.250513  
4          131     694.459277     676.680029  

[5 rows x 34 columns]

In [2209]:
# Get Mean and SD for the  trial

step = ['Rstep_time','Lstep_time','Rstep_length','Lstep_length', 'Rstep_width', 'Lstep_width',
        'Rstance%', 'Lstance%', 'Rswing%', 'Lswing%',
        'Rstride_time', 'Lstride_time', 'Rstride_length', 'Lstride_length']
rows = []

for col in step:
    df_attr = getattr(strike_df, col)
    row = pd.DataFrame({col+"_Avg":[df_attr.mean()], 
                        col+"_SD":[df_attr.std()]
                       }, index = [filename])
    rows.append(row)

step_df = pd.concat(rows, axis=1)
step_df

Rstep_time_Avg  Rstep_time_SD  Lstep_time_Avg  Lstep_time_SD  \
G06Trial07B       72.428571        10.2604       73.669951       9.927182   

             Rstep_length_Avg  Rstep_length_SD  Lstep_length_Avg  \
G06Trial07B        339.615234       100.885082        376.485942   

             Lstep_length_SD  Rstep_width_Avg  Rstep_width_SD  ...  \
G06Trial07B        65.773857        48.911024       33.847222  ...   

             Lswing%_Avg  Lswing%_SD  Rstride_time_Avg  Rstride_time_SD  \
G06Trial07B    30.965526    2.738825        145.866337        16.491124   

             Lstride_time_Avg  Lstride_time_SD  Rstride_length_Avg  \
G06Trial07B        146.098522        16.506529          714.629537   

             Rstride_length_SD  Lstride_length_Avg  Lstride_length_SD  
G06Trial07B          109.39221          716.101176         120.905965  

[1 rows x 28 columns]

In [2210]:
if not os.path.exists('step1.csv'):
    step_df.to_csv('step1.csv', index=filename, mode='w')
else:
    step_df.to_csv('step1.csv', index=filename, mode='a')